on:
  workflow_call:
    secrets:
      env-vars:
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Duild with ${{secrets.env-vars}}
