name: GitHub Actions Demo ${{ github.ref_name}}
on: [push]
jobs:
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set env vars (PROD) ${{ github.ref_name}}
      if: ${{ github.ref_name == 'main'}}
      id: step_one
      run: |
        cat << EOF > $GITHUB_ENV
        ENVIRONMENT=prod
        TAG=${{secrets.SECRET1}}
        EOF
    - name: Set env vars (DEV)
      if: ${{ github.ref_name == 'dev'}}
      id: step_two
      run: |
        cat << EOF > $GITHUB_ENV
        ENVIRONMENT=dev
        TAG=superdev
        EOF
    - name: Deploy!!
      run: echo "ENVIRONMENT 1 IS ${{env.ENVIRONMENT}}, TAG IS ${{env.TAG}}"
    - run: echo "TAG IS ${{env.TAG}}"
