name: GitHub Actions Demo
on: [push]
jobs:
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set env vars (PROD)
      if: ${{ github.ref_name == 'main'}}
      id: step_one
      run: |
        echo "ENVIRONMENT=prod" >> $GITHUB_ENV
    - name: Set env vars (DEV)
      if: ${{ github.ref_name == 'dev'}}
      id: step_two
      run: |
        echo "ENVIRONMENT=dev" >> $GITHUB_ENV
    - name: Deploy!!
      run: echo "ENVIRONMENT 1 IS ${{env.ENVIRONMENT}}"
    - run: echo "ENVIRONMENT 2 IS ${{env.ENVIRONMENT}}"
