on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      env:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure AWS credentials
        run: echo ${{inputs.username}}, ${{secrets.env}}, ${{secrets.TEMP}}, 
      - name: Login to Amazon ECR
        run: ''
      - name: Set the workflow environment vars (DEV)
        run: ''
      - name: Build, tag, and push the image to Amazon ECR
        run: ''
      - name: Pull and run the container on EC2 instance
        run: ''
