name: Deploy
on:
  workflow_call:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: ''

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure AWS credentials

      - name: Login to Amazon ECR

      - name: Set the workflow environment vars (DEV)

      - name: Build, tag, and push the image to Amazon ECR

      - name: Pull and run the container on EC2 instance
