name: Development
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Development Build and Test 
    uses: ./.github/workflows/build.yml
  
  aws-ecr:
    name: Development Push to AWS ECR 
    needs: build
    uses: ./.github/workflows/aws_ecr.yml
    
  run-ec2:    
    name: Development Deploy
    needs: aws-ecr
    uses: ./.github/workflows/run_ec2.yml
    with:
      username: USER
    secrets:
      env: DEV
