name: Development
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Development Build and Test 
    uses: ./.github/workflows/build.yml
  
  ecr-push:
    name: Development Push to AWS ECR 
    needs: build
    uses: ./.github/workflows/ecr_push.yml
    
  run-ec2:    
    name: Development Run EC2
    needs: ecr-push
    uses: ./.github/workflows/run_ec2.yml
    with:
      username: USER
    secrets:
      env: DEV
