name: Development
on:
  push:
    branches:
      - dev
jobs:
  set-env-vars:
    name: Set env vars
    uses: ./.github/workflows/set-env-vars.yml
    secrets:
      google-client-secret: SECRET-1
      flags-environment-key: SECRET-2
    
  build:
    name: Development Build and Test 
    needs: set-env-vars
    uses: ./.github/workflows/build.yml
    secrets:
      env-vars: ${{needs.set-env-vars.outputs.env-vars}}
  
  ecr-push:
    name: Development Push to AWS ECR 
    needs: build
    uses: ./.github/workflows/ecr_push.yml
    
  run-ec2:    
    name: Development Run EC2
    needs: ecr-push
    uses: ./.github/workflows/run_ec2.yml
    with:
      username: USER
    secrets:
      env: DEV
