name: Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Production Build and Test 
    uses: ./.github/workflows/build.yml
  
  ecr-push:
    name: Production Push to AWS ECR 
    needs: build
    uses: ./.github/workflows/ecr_push.yml
          
  run-ec2:    
    name: Production Run EC2
    needs: ecr-push
    uses: ./.github/workflows/run_ec2.yml
    with:
      username: USER
    secrets:
      env: PROD
