on:
  push:
    branches:
      - main
jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    steps:
    - name: Build the app
      uses: ./.github/workflows/build.yml
      
    - name: Deploy to Production
      uses: ./.github/workflows/deploy.yml
      with:
        username: USER
        secrets: PROD
