on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  deploy:
    name: Production
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      username: USER
    secrets:
      env: PROD
