on:
  push:
    branches:
      - main
jobs:
  build:
    name: Production:Build
    uses: ./.github/workflows/build.yml
  deploy:    
    name: Production:Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      username: USER
      secrets: PROD
