name: Set env vars

on:
  workflow_call:
    secrets:
      google-client-secret:
        required: true
      flags-environment-key:
        required: true

    outputs:
      env-vars:
        value: ${{ jobs.set-env-vars.outputs.env-vars }}

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    outputs:
      env-vars: ${{ steps.env-vars.outputs.env-vars }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables into the .env file
        id: env-vars
        run: |
          ENV_VARS=GOOGLE_CLIENT_SECRET=${{ secrets.google-client-secret }}
          echo "::set-output name=env-vars::$ENV_VARS"
