name: Staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Staging Build and Test 
    uses: ./.github/workflows/build.yml
  
  ecr-push:
    name: Staging Push to AWS ECR 
    needs: build
    uses: ./.github/workflows/ecr_push.yml
    
  run-ec2:    
    name: Staging Run EC2
    needs: ecr-push
    uses: ./.github/workflows/run_ec2.yml
    with:
      username: USER
    secrets:
      env: STAGING
